# Generated by Django 5.2.8 on 2026-03-15 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customer_table_auditlog_internalmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalShareConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=2, default=1000.0, max_digits=15)),
                ('commission_percentage', models.DecimalField(decimal_places=4, default=0.01, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='internalmessage',
            name='recipient_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff Member'), ('accountant', 'Accountant'), ('partner', 'Partner'), ('receptionist', 'Receptionist')], max_length=50),
        ),
        migrations.CreateModel(
            name='PartnerShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_shares', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('total_investment', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShareTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('amount_shares', models.DecimalField(decimal_places=4, max_digits=15)),
                ('price_per_share', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('commission_deducted', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
