# Generated by Django 5.2.8 on 2026-03-15 20:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_globalshareconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharetransaction',
            name='accountant_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharetransaction',
            name='accountant_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_accountant_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharetransaction',
            name='admin_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharetransaction',
            name='admin_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_admin_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharetransaction',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_share_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharetransaction',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharetransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('accountant_approved', 'Accountant Approved'), ('approved', 'Approved (Final)'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='globalshareconfig',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0001'), max_digits=5),
        ),
    ]
