# Generated by Django 6.0.5 on 2026-05-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'managed': False},
        ),
    ]
