# Generated by Django 6.0.5 on 2026-05-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_payment_options_alter_sale_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='payment',
        ),
        migrations.AlterModelTable(
            name='sale',
            table='sale',
        ),
    ]
