# Generated by Django 6.0.5 on 2026-05-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_employee_options_alter_station_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='station',
            table='station',
        ),
    ]
