# Generated by Django 6.0.5 on 2026-05-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carwashbooking',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='carwashservice',
            options={'managed': False},
        ),
    ]
