# Generated by Django 6.0.5 on 2026-05-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_carwashbooking_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carwashbooking',
            table='car_wash_booking',
        ),
        migrations.AlterModelTable(
            name='carwashservice',
            table='car_wash_service',
        ),
    ]
