# Generated by Django 6.0.5 on 2026-05-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_alter_loyaltyredemption_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loyaltyredemption',
            table='loyalty_redemption',
        ),
        migrations.AlterModelTable(
            name='loyaltyreward',
            table='loyalty_reward',
        ),
    ]
