# Generated by Django 6.0.5 on 2026-05-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fueldelivery',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fueltype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pump',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tank',
            options={'managed': False},
        ),
    ]
