# Generated by Django 6.0.5 on 2026-05-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_fueldelivery_options_alter_fueltype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fueldelivery',
            table='fuel_delivery',
        ),
        migrations.AlterModelTable(
            name='fueltype',
            table='fuel_type',
        ),
        migrations.AlterModelTable(
            name='pump',
            table='pump',
        ),
        migrations.AlterModelTable(
            name='tank',
            table='tank',
        ),
    ]
